name: Creating Vanilla Sounds Resource Pack
run-name: Create Vanilla Sounds Resource Pack for all Minecraft Versions
on: 
  schedule:
    - cron: "*/10 * * * *" 
concurrency:
  group: "Main"
  cancel-in-progress: false
jobs:
  main:
    name: Main
    runs-on: windows-latest
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ github.token }}
      MODRINTH_VS_API: ${{ secrets.MODRINTH_VS_API }}
      MODRINTH_VS_PAT: ${{ secrets.MODRINTH_VS_PAT }}
    steps:
      - run: python main.py
